stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/ 
test:
  stage: test
  script:
     - npm install
     - npm run headless:test
 

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/Employee-Management

    
deploy:
  stage: deploy
  script:
    - aws s3 sync dist/Employee-Management "s3://techverito-angular-meetup-demo" --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
  dependencies:
    - build
  
